/*
 * generated by Xtext 2.16.0
 */
package org.xtext.tColab.turn.ide

import org.xtext.tColab.turn.ide.server.codeActions.TurnCodeActionService
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2

/**
 * Use this class to register ide components.
 */
class TurnIdeModule extends AbstractTurnIdeModule {
	
	def Class<? extends ICodeActionService2> bindICodeActionService2() {
		TurnCodeActionService
	}
}
