/*
 * generated by Xtext 2.22.0
 */
package org.xtext.tColab.turn


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TurnRuntimeModule extends AbstractTurnRuntimeModule {
}
