/*
 * generated by Xtext 2.22.0
 */
package org.xtext.tColab.turn


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TurnStandaloneSetup extends TurnStandaloneSetupGenerated {

	def static void doSetup() {
		new TurnStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
